### PR TITLE
Feature/mobile design incidents

### PR DESCRIPTION
**Pull request by didi-codes**
# Description
Implemented all breakpoints for media queries for the incidents page and navbar page
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?
I have tested the media queries on my browser using dev tools
- [ ] `npm test`

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by aleksandr-ardanov** [comment]
Please clarify what changes were made with Admin Dashboard page and AntTable. It seems like  you (Didi) pushed only CSS changes but i see some commits from Anas(i don't know how it's happened) and it doesn't mentioned in description.

**Comment by didi-codes** [comment]
> Please clarify what changes were made with Admin Dashboard page and AntTable. It seems like you (Didi) pushed only CSS changes but i see some commits from Anas(i don't know how it's happened) and it doesn't mentioned in description.

Hey Alex I was working with Anas to implement it so I was working on his branch but I have not made any of those changes and he has yet to push those changes as well

**Review by aleksandr-ardanov — APPROVED** [review]

**Comment by mhuckstepp** [comment]
> > Please clarify what changes were made with Admin Dashboard page and AntTable. It seems like you (Didi) pushed only CSS changes but i see some commits from Anas(i don't know how it's happened) and it doesn't mentioned in description.
> 
> Hey Alex I was working with Anas to implement it so I was working on his branch but I have not made any of those changes and he has yet to push those changes as well

@didi-codes it does look like there are significant changes to the AntTable in this PR. If you did not intend for that, this may be able to help https://stackoverflow.com/questions/61354821/github-including-other-peoples-commits-in-my-pull-request

**Review by mhuckstepp — APPROVED** [review]
Looks good.

**Pull request merged**
