### PR TITLE
changed color of white line break, but kept it for functionality.

### PR DESCRIPTION
**Pull request by n0tybynature**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] `npm test`

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by alvin-joseph — APPROVED** [review]
This change looks great! Nice work!

**Review by RyanFikejs — APPROVED** [review]
Thanks for explaining the package-lock.json thing for me guys. Between that and a little digging it makes sense now. Alvin, thanks for giving out some good tips on what to do here, I strongly suspected that we didn't need that whole swap to occur for those dependencies,

**Comment by RyanFikejs** [comment]
Thanks for cleaning up the commit guys!

**Comment by RyanFikejs** [comment]
Sorry, accidentally closed instead of merging the first time -_-
late night...

**Pull request merged**
