### PR TITLE
Bugfix - approved incidents list was also showing unapproved incidents, now showing properly

### PR DESCRIPTION
**Pull request by ahmedseragcodes**
## Loom video link

https://www.loom.com/share/ac4d70d3394d483a93d0b532a6c49cde

## Slack Thread

https://lambda-students.slack.com/archives/C02C8UXQZPY/p1631145405206600

# Description

fixed bug where approved incidents list was also showing unapproved incidents list

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Status

- [ ] Complete, tested in local deployment, needs unit tests 

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by kcjerrell** [comment]
That fixes it. It might be DRYer though if you pulled the {adding ? ...} section out of approved/unapproved and put it on its own.

```
{adding && <AddIncident>}
{listType === 'unapproved && <Incidents>}
{listType === 'approved && <ApprovedIncidents>}
```

**Review by kcjerrell — APPROVED** [review]
That fixes it. It might be DRYer though if you pulled the {adding ? ...} section out of approved/unapproved and put it on its own.

```
{adding && <AddIncident>}
{listType === 'unapproved && <Incidents>}
{listType === 'approved && <ApprovedIncidents>}
```

**Review by imjeremiah — APPROVED** [review]
Bug is fixed, and all seems right again. I agree with Kelly's assessment or possibly refactoring the code to make it more DRY. No merge conflicts. Approved.

**Comment by paulstgermain** [comment]
As this is a simple fix that still included a thorough video walkthrough of the bug, I'll be approving and merging this PR straight away! I do, however, agree with Kelly & Jeremiah's stances regarding making the code dryer, but this bug fix is of top importance, so let's strive for that in another PR down the line!

**Pull request merged**
