### PR TITLE
Bug/standardize forms AddIncident form

### PR DESCRIPTION
**Pull request by Ethan-Edmond**
# Description

[Explanation Video](https://www.loom.com/share/5a49fb82cd274ceda810bc452aa5bb5b)
This redoes the AddIncident form in the way that I plan to make the rest of them. Not much styling was actually done as it's pretty much just the default styles for the ant design components. I added a bit of form validation, but I still need to figure out what I'm doing there.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [X] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [X] `npm test`

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Review by austin-carman — APPROVED** [review]
Looks great! Clean and easy to read code, definitely makes the form look better and glad to see there is some form validation.

**Comment by imjeremiah** [comment]
Ethan, I see this is marked for review. The changes look great, the updated form looks far better in comparison to the old, as you demo'd in the explanation video. I do have a couple of questions: 

Would the PR make better sense if the title was renamed to something like "Bug/standardize AddIncident form" rather than "Bug/standardize forms"? I get the sense you are going to push separate PRs for each form you standardize. 

Is the AddIndicent form ready to ship as is, without completed validation? Will that be a future feature?

**Comment by Ethan-Edmond** [comment]
Jeremiah, I did have the intention to push separate PRs for each form. I will change the title to be more descriptive. The AddIncident form is not ready to ship. The form did not have validation before, and the validation I put on it is not finished. I feel like it's kinda out of the scope of this PR. The thing I would need to complete validation here is to figure out what is ok for an incident not to have. Do we want every incident in the database to have a description, and gps coordinates, .etc? I feel like all are required, but I don't really know if that's the case, so I stopped myself there.

**Review by ooladuwa — APPROVED** [review]
Ethan, great job. The code is definitely cleaner and the horizontal vs. vertical orientation of the city/state inputs "feels" better from a user perspective.

**Review by imjeremiah — APPROVED** [review]
Ethan, thanks for the clarity. I understand now we're separating standardization (UX) and validation (FE). For this PR we can focus only on standardization, which has been reviewed in previous comments. The new title is much more descriptive. No merge conflicts. Approved.

**Pull request merged**
