### PR TITLE
Feature/graph categories

### PR DESCRIPTION
**Pull request by victoriamount**
# Description

Fixes issue where the Pie and Horizontalbar graphs were broken due to BE change to the way categories were structured and what those categories were. Also fixes issue where values represented in Horizontalbar were hardcoded, random values. Horizontalbar is temporarily moved to the PieGraph file to be visible.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [X] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [X] `npm run test`

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My code has been reviewed by at least one peer
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Comment by victoriamount** [comment]
What am I doing wrong that makes my old commits be strung along with my new PRs 😬. Old file changes are not included, just the commit messages.

**Comment by mcolsen** [comment]
The PieGraph component appears to be broken for me, but I'm not sure if there's something wrong on my end. The animation where the chart expands into a circle begins and then quickly disappears.

**Comment by victoriamount** [comment]
> The PieGraph component appears to be broken for me, but I'm not sure if there's something wrong on my end. The animation where the chart expands into a circle begins and then quickly disappears.

Doesn't happen on my end, I'll ask Will or Sam to check it out?

Update: Works for Will & Sam

**Review by willwearing — APPROVED** [review]
Looks and works great on my end. Thanks!

**Comment by mcolsen** [comment]
> > The PieGraph component appears to be broken for me, but I'm not sure if there's something wrong on my end. The animation where the chart expands into a circle begins and then quickly disappears.
> 
> Doesn't happen on my end, I'll ask Will or Sam to check it out?
> 
> Update: Works for Will & Sam

Huh, strange. I'll clone a clean copy and hope everything works 🤞

**Pull request merged**
