### PR TITLE
Bug/force rank

### PR DESCRIPTION
**Pull request by kcjerrell**
# Description

[Explanation video](https://www.loom.com/share/8a6828d078b1460eab50cd94b8c3afc9)

This pull request is to fix inconsistent values for the "force_rank" property on incident data.

In the existing incident data, values for force_rank look like this:
```force_rank: "Rank 4"```

However, many of the components in the front-end were expecting values that looked like this:
```force_rank: "Rank 4 - Chemical & Electric"```

The following components were affected by this inconsistency:
* The bar graph on the front page
* The missing pie graph on the Graph page
* Incident filtering on the Incident Reports page
* Edit incident
* Add incident
* Twitter form

Any usage of the longer force_rank value throughout the front-end project has been updated to use the shorter form that the incident data currently uses.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [x] `npm test`

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by lgarcia2689 — APPROVED** [review]
Reviewed changes made by @kcjerrell verified & tested that work properly

**Review by ahmedseragcodes — COMMENTED** [review]
Hmmm, it looks like there's a merge baked into this PR, which is worrisome.

**Comment by kcjerrell** [comment]
That's because handoff.md was added after I started a new branch, and the other merges were combining branches that were dealing with the same issue. I don't think the history will create an issue, and in the end, it's only the 7 changed files that will be merged back into main.

(Okay I see the section on merging/rebasing in Canvas now. I can redo it on a clean branch)

**Comment by paulstgermain** [comment]
This PR still needs one more review - can we get one ASAP? :)

**Review by Ethan-Edmond — APPROVED** [review]
Ok, so I get how this fixes the bugs and why you changed what. Your explanation is good. You probably could have changed them all in one 'changed force_rank' commit, but it looks like you realized that later. I would like to know how you found this bug.

**Comment by Ethan-Edmond** [comment]
Also Nice job!

**Review by imjeremiah — APPROVED** [review]
Great video explanation of the bug, and the demo of the features working once bug was corrected. I noticed the conversation about the merge in the PR, and agree with the Release Manager that PR is fine as is. Good documentation of changes, no merge conflicts. Approved.

**Review by paulstgermain — APPROVED** [review]
## Video Walkthrough Feedback

This was a nicely represented PR! I loved that you came prepared with plenty of examples - showing the application as it was, explaining the problem you were seeking to resolve, showing where the error in the code was, and even demonstrating your method of resolving this issue, before showing the final, working result. You also explained everything in such technical detail that I think an interviewer or manager would be thrilled to receive a similar presentation, so keep up this style of walking through your work, you're on the right track!

## Code Review

This is also a clean, simple change in the codebase. By simply aligning the expected variables on the front-end components to match with the schema currently in use by the back-end, you've effectively repaired several non-functional components to working condition - and without introducing any errors, comments, or dead-end code - nice work!

For the reasons listed above, approving and merging this PR!

**Pull request merged**
