### PR TITLE
Feature/media queries about footer

### PR DESCRIPTION
**Pull request by didi-codes**
# Description
Added the new logo approved by welton
Media query breakpoints for footer.css complete 
Fixes # (issue)
Functionality for mobile
## Type of change
Design change for mobile functionality

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [ ] `npm test`

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by mhuckstepp** [comment]
@didi-codes I also see a lot of changes to components outside of the scope of this pull request. I think it is the same issue described here https://sirolad.medium.com/other-peoples-commit-in-my-pull-request-github-afc1fa7528ea

**Comment by aleksandr-ardanov** [comment]
There is many changes on Admin Page and it doesn't mentioned in description, same issue has happened with your previous pull request.

**Comment by didi-codes** [comment]
> There is many changes on Admin Page and it doesn't mentioned in description, same issue has happened with your previous pull request.

The issue has been fixed

**Comment by didi-codes** [comment]
> @didi-codes I also see a lot of changes to components outside of the scope of this pull request. I think it is the same issue described here https://sirolad.medium.com/other-peoples-commit-in-my-pull-request-github-afc1fa7528ea

So this worked but now there is a merge conflict

**Comment by aleksandr-ardanov** [comment]
> > @didi-codes I also see a lot of changes to components outside of the scope of this pull request. I think it is the same issue described here https://sirolad.medium.com/other-peoples-commit-in-my-pull-request-github-afc1fa7528ea
> 
> So this worked but now there is a merge conflict

It seems like you removed commits but files stayed unchanged (files from AdminDashboard produce conflicts)

**Review by didi-codes — COMMENTED** [review]
Files that are not needed causing merge conflicts were deleted

**Pull request closed without merging**
