### PR TITLE
final push to the change the graph dates

### PR DESCRIPTION
**Pull request by didi-codes**
# Description
Changed the graph dates
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [ ] `npm test`

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by mhuckstepp — APPROVED** [review]
Nicely scoped cleanup PR

**Review by aleksandr-ardanov — COMMENTED** [review]
Are you sure dates should be hard coded?

**Comment by didi-codes** [comment]
> Are you sure dates should be hard coded?

Yes confirmed with Anas just the line graph needs the date dynamically set

**Comment by aleksandr-ardanov** [comment]
> > Are you sure dates should be hard coded?
> 
> Yes confirmed with Anas just the line graph needs the date dynamically set

Good!

**Review by aleksandr-ardanov — APPROVED** [review]

**Review by wberman27 — APPROVED** [review]

**Pull request merged**
