### PR TITLE
Made changes to the map clusters on the homepage.

### PR DESCRIPTION
**Pull request by wberman27**
# Description

Made changes to the map clusters on the homepage.

Fixes # (issue)

1. Made clusters smaller
2. Transition time on zoom is faster
3. Removed compass nav control
4. Increased incidents shown on cluster click

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [ ] `npm test`

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by StephanieEnciso — APPROVED** [review]
Clean code. The changes make the map clusters look a lot better.

**Review by aleksandr-ardanov — APPROVED** [review]
Good, clean code with the proper amount of commits.

**Review by CerritoCode0101 — APPROVED** [review]
Minor changes, nothing seems to be conflicting, clean code

**Review by didi-codes — APPROVED** [review]
I approve of these changes, I feel they will allow our map to work correctly

**Pull request merged**
