### PR TITLE
styling fix on incident reports page

### PR DESCRIPTION
**Pull request by BradleyHubbs**
# Description
- Left aligned elements on incident reports page as per Franks feedback.
- Set max width on incident reports page so the page doesn't stretch indefinitely on large screens.

Fixes #
- [x] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

All tests pass

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by davarg5 — APPROVED** [review]
Looks good

**Review by ShahJalpa — APPROVED** [review]
I like that how quickly you changed the style. Perfect

**Review by ryanhammer — APPROVED** [review]
Changes look good; appreciate the quick implementation of what was discussed at Product Review and the narrow focus of the PR.

**Review by leon-nasswetter — APPROVED** [review]
Good stuff

**Review by danielbkim — APPROVED** [review]

**Pull request merged**
