### PR TITLE
Feature/Display map incidents panel by default

### PR DESCRIPTION
**Pull request by imjeremiah**
# Description

[Video Explanation](https://www.loom.com/share/f0d59ddc16d84caabe5bd1763ba0a253)

This PR adds functionality to the home page map as discussed in the last Product Meeting. The goal of the map is for both exploration and information. Currently, the map's main function is only for exploration, as the incident report panel is closed by default. Instead of stumbling onto the informational panel feature, this PR opens the panel by default, so both the map and incident panel are always displayed. The PR leaves the panel as a toggle, so it can be closed if a user desires. 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Change Status

- [ ] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [ ] `npm test`

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by lgarcia2689 — APPROVED** [review]
Great work

**Review by austin-carman — APPROVED** [review]
Good work. Simple fix with big results

**Review by Ethan-Edmond — APPROVED** [review]
Looks good. Maybe leave the ticket around so that the next team gets the sidebar stuff we talked about. Approved.

**Review by ooladuwa — APPROVED** [review]
Great job. Small change but impactful. Thanks.

**Pull request merged**
