### PR TITLE
Fixed search input (Combobox) collapsing issue from Graphs Page

### PR DESCRIPTION
**Pull request by jossters**
# Description
Screen Shot 2021-08-11 at 7 32 22 PM
Fixes # (issue)
There was an issue with the search input (Combobox) collapsing when either typed into or when selecting a state on the graphs page.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [x] Complete, but not tested (may need new tests)

# How Has This Been Tested?

- [x] `npm test`

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by alvin-joseph — APPROVED** [review]
Nice work finding the specific search box! It was definitely a strange bug but I am glad you were able to fix it!

**Review by devin-mitchell — COMMENTED** [review]
Just wondering if the node_modules css is changing the search bar for any other media queries.  If so you'll have to overwrite those as well.

**Comment by jossters** [comment]
> Just wondering if the node_modules css is changing the search bar for any other media queries. If so you'll have to overwrite those as well.

I checked the  media queries  and all are working just fine.

**Review by devin-mitchell — APPROVED** [review]
Awesome looks Great!

**Pull request merged**
