### PR TITLE
changed color of hover from blue to human rights first's lighter orange.

### PR DESCRIPTION
**Pull request by n0tybynature**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

- [x ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge

# Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts

### CODE REVIEW

**Review by jossters — COMMENTED** [review]
Great work, I see the card on Trello for consistent hover behavior throughout the site, but I don't see what color we choose as a team on Trello can you please confirm that this is the correct color. This decision may have been made in a Zoom meeting, but not documented.

**Review by devin-mitchell — COMMENTED** [review]
Could be nice to throw a quick screen shot in the PR so we can see the implementation of your work.

**Comment by n0tybynature** [comment]
There wasn't any agreement on the color as a whole, so I decided to just use a color that is in the color scheme. We can change it to anything, it was just noted to change, not anything specific.
colorchange

**Comment by devin-mitchell** [comment]
Oh nice!  I think that looks great!

**Comment by alvin-joseph** [comment]
That color looks great! I did actually change the hover style already though. I was talking with Ryan Dill and we decided to change it to a white underline/white text on hover. If you guys want to change it to this style then you may have to remove the underline styling on hover that I added.

**Comment by Iamlegend-Imani** [comment]
Yea definitely a screenshot would be helpful to add to the PR

**Review by Gavin-Rilee — APPROVED** [review]
I love the color!

**Review by nickcabuno — APPROVED** [review]
color looks great

**Review by JAaron93 — APPROVED** [review]
Orange is probably the best color you could have chosen for this.

Absolutely aesthetic

**Pull request merged**
