### PR TITLE
updated names requested by cohort members

### PR DESCRIPTION
**Pull request by devin-mitchell**
# Description

Just had a couple requests to change peoples names in the About page.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [ ] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [ ] `npm test`

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by Iamlegend-Imani — APPROVED** [review]
Thanks @devin-mitchell

**Review by Iamlegend-Imani — APPROVED** [review]
Thanks @devin-mitchell

**Comment by alvin-joseph** [comment]
request
Hey I saw this comment on the last PR. Just wanted to make sure you updated these names as well

**Comment by devin-mitchell** [comment]
> request
> Hey I saw this comment on the last PR. Just wanted to make sure you updated these names as well

Just saw this!  My bad!  Got it fixed :)

**Review by alvin-joseph — APPROVED** [review]
Nice! Everything looks great!

**Review by Iamlegend-Imani — COMMENTED** [review]
Thanks @devin-mitchell

**Pull request merged**
