### PR TITLE
changed color of white line to blue, kept the line break to help with…

### PR DESCRIPTION
**Pull request by n0tybynature**
… the functionality of the page.

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] `npm test`

# Checklist

- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by RyanFikejs** [comment]
Tony, I'm unaware of a few things on the web side, can you give me a more detailed explanation of what exactly the package-lock.json file is and why we're eliminating 33,000+ lines of code and then adding 400+? Was this something that you committed and pushed, then removed from your pull request? I would guess that we only need be concerned with the css file.

**Comment by n0tybynature** [comment]
package-lock.json is automatically generated for any operations where npm modifies either the node_modules tree, or package.json. It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.

The package-lock.json file is being updated every single time you call npm install since NPM 5.1.

Ran npm install and did a npm audit fix, so all the files inside the package-lock was probably updated.

**Comment by alvin-joseph** [comment]
So it looks like when you did a git add, you added the package-lock.json file as well. When you do the git add all you have to add is the specific file you modify. In this case you would just do git add src/components/Stats/Stats.css. That way you won't have such a huge commit.

**Comment by n0tybynature** [comment]
ahh i gotcha. lemme fix that.

**Pull request closed without merging**
